### PR TITLE
add-median

### PR DESCRIPTION
**Pull request by ShigekiKarita**

### CODE REVIEW

**Comment by jmh530** [comment]
Sorting to get the median is one of the slower selection algorithms, though it is relatively straightforward to write a quantile function that way. Phobos has a topN function in std.algorithm that you might look at also.

https://en.wikipedia.org/wiki/Selection_algorithm

**Comment by 9il** [comment]
We need our own topN based on betterC port of binary heap
http://docs.algorithm.dlang.io/latest/mir_container_binaryheap.html
PR is wellcome :-)

**Comment by ShigekiKarita** [comment]
Thanks. I will look at that.

**Comment by 9il** [comment]
please ignore my comment about binary heap. Probably for topN where N = L/2 binary heap is not required

**Pull request merged**
